version: '3.3'

services:
  lookout:
    image: "srcd/lookout:latest"
    network_mode: "host"
    depends_on:
      - postgres
    environment:
      GITHUB_USER: "idanlesh"
      GITHUB_TOKEN: "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"
    ports:
      - "10301:10301"
    entrypoint: ["/bin/sh"]
    # sleep because container with db is up but the db itself doesn't accept connections yet
    command: ["-c", "sleep 5 && lookoutd migrate && lookoutd serve"]
    volumes:
      - ./config.yml:/config.yml
        #dummy:
        #    image: "srcd/lookout-dummy-analyzer:latest"
        #    network_mode: "host"
        #    ports:
        #      - "9930:9930"
  bblfsh:
    image: "bblfsh/bblfshd:v2.12.1-drivers"
    privileged: true
    ports:
      - "9432:9432"
  postgres:
    image: "postgres:alpine"
    command: postgres -c listen_addresses='*'
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lookout
